# Generated by Django 4.1.5 on 2023-01-31 18:41

from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0005_alter_customerphone_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RawMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='نام')),
                ('man_factory', models.CharField(max_length=30, verbose_name='کارخانه سازنده')),
            ],
            options={
                'verbose_name': 'ماده اولیه',
                'verbose_name_plural': 'ماده اولیه',
            },
        ),
        migrations.CreateModel(
            name='BuyRawMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', django_jalali.db.models.jDateTimeField(verbose_name='تاریخ')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.employee', verbose_name='کارمند')),
            ],
            options={
                'verbose_name': 'ثبت خرید ماده اولیه',
                'verbose_name_plural': 'ثبت خرید ماده اولیه',
            },
        ),
        migrations.CreateModel(
            name='BuyRawItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='تعداد')),
                ('price', models.IntegerField(verbose_name='قیمت')),
                ('buy_rawmaterial', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='buyraw.buyrawmaterial', verbose_name='آیدی خرید ماده اولیه')),
                ('raw_material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='buyraw.rawmaterial', verbose_name='ماده اولیه')),
            ],
            options={
                'verbose_name': 'ردیف ماده اولیه',
                'verbose_name_plural': 'ردیف ماده اولیه',
            },
        ),
    ]
