# Generated by Django 4.1.5 on 2023-01-30 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_employee_options_alter_employee_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeePhone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=11, verbose_name='شماره تماس')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.employee', verbose_name='کارمند')),
            ],
            options={
                'verbose_name': 'شماره تماس کارمند',
                'verbose_name_plural': 'شماره تماس کارمندان',
            },
        ),
        migrations.CreateModel(
            name='CustomerPhone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=11, verbose_name='شماره تماس')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.employee', verbose_name='کارمند')),
            ],
            options={
                'verbose_name': 'شماره تماس مشتری',
                'verbose_name_plural': 'شماره تماس مشتریان',
            },
        ),
    ]
