# Generated by Django 4.1.5 on 2023-01-30 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_customerphone_customer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customerphone',
            options={'verbose_name': 'شماره تماس مشتری', 'verbose_name_plural': 'شماره تماس مشتری'},
        ),
        migrations.AlterModelOptions(
            name='employeephone',
            options={'verbose_name': 'شماره تماس کارمند', 'verbose_name_plural': 'شماره تماس کارمند'},
        ),
    ]
