# Generated by Django 4.1.5 on 2023-01-19 17:42

from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_alter_employee_options_alter_employee_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(1, 'روغن حیوانی'), (2, 'زعفران')], verbose_name='نوع')),
                ('weight', models.IntegerField(verbose_name='وزن(گرم)')),
                ('product_serie', models.IntegerField(verbose_name='سری ساخت')),
                ('man_date', django_jalali.db.models.jDateField(verbose_name='تاریخ تولید')),
                ('exp_date', django_jalali.db.models.jDateField(verbose_name='تاریخ انقضا')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerBuy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', django_jalali.db.models.jDateTimeField()),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.customer', verbose_name='مشتری')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.employee', verbose_name='کارمند')),
            ],
        ),
        migrations.CreateModel(
            name='BuyItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='تعداد')),
                ('price', models.IntegerField(verbose_name='قیمت')),
                ('customerbuy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='custorder.customerbuy', verbose_name='آیدی خرید')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='custorder.product', verbose_name='محصول')),
            ],
        ),
    ]
