# Generated by Django 4.1.5 on 2023-01-30 10:04

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('custorder', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='buyitem',
            options={'verbose_name': 'ردیف خرید', 'verbose_name_plural': 'ردیف خرید'},
        ),
        migrations.AlterModelOptions(
            name='customerbuy',
            options={'verbose_name': 'ثبت سفارش', 'verbose_name_plural': 'ثبت سفارش'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'محصول', 'verbose_name_plural': 'محصولات'},
        ),
        migrations.AlterField(
            model_name='customerbuy',
            name='datetime',
            field=django_jalali.db.models.jDateTimeField(verbose_name='تاریخ'),
        ),
    ]
