# Generated by Django 4.1.5 on 2023-01-30 13:33

from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0005_alter_customerphone_options_and_more'),
        ('custorder', '0002_alter_buyitem_options_alter_customerbuy_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='تعداد')),
                ('datetime', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.employee', verbose_name='کارمند')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='custorder.product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'ثبت تولید',
                'verbose_name_plural': 'ثبت تولید',
            },
        ),
    ]
